######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 1 18:53:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += epoll_server.h socketheads.h zepoll.h \
    task.h \
    channel.h \
    user.h
SOURCES += epoll_server.cpp main.cpp zepoll.cpp \
    task.cpp \
    channel.cpp \
    user.cpp
